# permissions for end users to edit podwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podwatcher-editor-role
rules:
- apiGroups:
  - watcher.example.com
  resources:
  - podwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.example.com
  resources:
  - podwatchers/status
  verbs:
  - get
