# permissions for end users to view podwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podwatcher-viewer-role
rules:
- apiGroups:
  - watcher.example.com
  resources:
  - podwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - watcher.example.com
  resources:
  - podwatchers/status
  verbs:
  - get
